name: Update Profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Update Age + Coding Years
      - name: Update Age + Coding Years
        run: |
          BIRTHDATE="2009-06-19"
          CODING_START_YEAR=2022

          TODAY=$(date +%s)
          CURRENT_YEAR=$(date +%Y)
          BIRTH=$(date -d "$BIRTHDATE" +%s)

          AGE=$(( (TODAY - BIRTH) / 31556952 ))
          CODING_YEARS=$(( CURRENT_YEAR - CODING_START_YEAR ))

          sed -i "s/<!-- AGE_START -->.*<!-- AGE_END -->/<!-- AGE_START -->$AGE<!-- AGE_END -->/" README.md
          sed -i "s/<!-- CODING_YEARS_START -->.*<!-- CODING_YEARS_END -->/<!-- CODING_YEARS_START -->$CODING_YEARS<!-- CODING_YEARS_END -->/" README.md

      # Commit changes
      - name: Commit README changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update profile stats"
          git push
